### ISSUE TITLE
Ability to convert speed

### ISSUE THREAD

**Issue by jrj2211** [jonahsnider/convert#295]
Looking through the docs I dont see any conversion types for speed. I often work in inches per second, but threejs uses meters so I have to convert. Would be great to get this built in or the ability to define custom units. If possible, I think a generic solution for this would be best where you can use any already defined length unit over any defined time unit instead of adding in specifically in/s, m/s, miles/h, etc...

With this, the dividend I guess could also be an angle... degrees/s, radians/m, etc.

**Comment by aetheryx** [comment]
@jonahsnider any updates on this?

**Comment by jonahsnider** [comment]
When this issue was first created I tried for a few hours to implement a system that allowed support for creating compound units. Unfortunately, I was unable to do so without compromising on performance, bundle size, and/or typesafety. Rather than release a feature that deviates from Convert's goals (being the fastest, smallest, typesafe-est unit conversion library available) I'd prefer to allow users to implement something like this themselves which suits their application's needs.
