### ISSUE TITLE
problem with rounding by all measures

### ISSUE THREAD

**Issue by Oleg55** [jonahsnider/convert#555]
Hello, a problem with rounding by all measures was found.
for example, if we take 10 square meters and translate them into square kilometers, we get 0.000009999999999999999, while if we take 11 we get the correct answer 0.000011, and so on for all metrics

**Comment by jonahsnider** [comment]
This slight loss in precision is because of how JavaScript defines floating point arithmetic (according to the IEEE 754 spec). While it is possible to avoid the loss in precision for operations like '10 square meters to square kilometers', it would require significant refactors to [how Convert works internally](https://github.com/jonahsnider/convert/blob/e81e9d66f95b44fa10e156e33c826c1213c841ab/packages/convert/src/converter.ts#L199). So, it doesn't really make sense for me to try changing this behavior.

I would recommend using something like `Number.prototype.toFixed()` to round the resulting number to a given level of precision:

```js
const result = convert(10, 'sq m').to('sq km');
const rounded = Number(result.toFixed(10)); // 10 digits of accuracy after the decimal point
console.log(rounded);
```
